name: Build check (Frontend, backend)

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
jobs:
  frontend-build:
    name: ğŸ³ Check Frontend, Backend
    runs-on: ubuntu-latest
    timeout-minutes: 8
    container: node:16
    steps:
      - name: ğŸ¤ Checkout
        uses: actions/checkout@v2
      # - name: âŒš Compile React.js production build
      #   run: |
      #     cd ./frontend
      #     npm i
      # npm run build
      - name: compile backend
        run: |
          cd ./backend
          touch .env
          echo '${{secrets.DATABASE_ENV}}' > .env
          npm i
          npm run build
